### ISSUE TITLE
How to use Move To Trash

### ISSUE THREAD

**Issue by Speedmod88** [jlesage/docker-filebot#81] opened 2023-01-09 09:00 UTC
Hi, since few update of Filebot, They added the MoveToTrash command when we double click on the movie name (in Original Filename Side) during Rename

it seem not working with your docker on UnRaid os

any clue if its on my side the reason why it doesnt work??

Thanks

**Comment by jlesage** [comment] 2023-01-10 03:01
This is a problem with FileBot itself.  I was able to reproduce the same issue with FileBot installed on a "normal" Ubuntu distro.  The following error is generated by FileBot:

```
The MOVE_TO_TRASH action is not supported on the current platform!
```

Can you report this issue on the FileBot forum?  For Linux we probably need a way to just remove the file, without sending it to a trash.

**Comment by Speedmod88** [comment] 2023-01-14 13:55
in pending in FileBot forum

**Comment by jlesage** [comment] 2023-01-16 01:43
For reference, this is the link to the discussion in FileBot forum: https://www.filebot.net/forums/viewtopic.php?f=6&t=13530

**Comment by jlesage** [comment] 2023-01-16 01:44
Looks like the behaviour has been "fixed" in FileBot.  I think we can close this issue.

**Closed by jlesage** 2023-01-16 01:44 UTC
