### ISSUE TITLE
net.filebot.util.prefs.sync=true

### ISSUE THREAD

**Issue by rednoah** [jlesage/docker-filebot#111] opened 2024-10-03 16:02 UTC
### Current Behavior

`net.filebot.util.prefs.sync=true` should be set on systems where the FileBot Desktop application is not typically closed via the `X` button, and likely to be killed suddenly via `SIGKILL` instead.

See https://www.reddit.com/r/unRAID/comments/1fu8q8i/filebot_saved_presets_not_saving/ for details. The user suggests that FileBot does not persist user settings if the container is stopped, which would be expected behaviour if FileBot is killed suddenly as user settings are only stored to file on close by default. The `net.filebot.util.prefs.sync=true` system property will instruct FileBot to sync settings to file immediately.

e.g.
```
-Djava.util.prefs.PreferencesFactory=net.filebot.util.prefs.FilePreferencesFactory \
-Dnet.filebot.util.prefs.file="$APP_DATA/prefs.properties" \
-Dnet.filebot.util.prefs.sync=true \
```

An orderly shutdown via `SIGTERM` or simulated "close window" events would be preferable of course but that might not be feasible.

### Environment

- OS:
- OS version:
- CPU:
- Docker version:
- Device model:
- Browser/OS:

### Container creation

x

### Container log

```text
x
```

**Comment by jlesage** [comment] 2024-10-15 01:10
Does this mean that FileBot doesn't handle the SIGTERM ?

**Comment by rednoah** [comment] 2024-10-16 13:22
I would assume that `SIGTERM` works, but you'll want to run a test to confirm. I didn't write the Java runtime, so I can neither confirm nor deny.

I'd be more interested in how `docker` handles container shutdown. Does it send `SIGTERM` to all processes running inside the container, and then wait a few seconds? Does this work as expected (i.e. close all windows) if the "main process" is a Desktop environment?

I don't even know how the user shuts down the container, presumably via some kind of `Stop` button of some kind of web interface. That said, the behaviour described in the original report does suggest that FileBot is killed suddenly, and not gracefully with `SIGTERM`.

**Comment by jlesage** [comment] 2024-10-17 02:05
When a container is stopped or restarted, the SIGTERM signal is sent to PID 1 inside the container. With this container, PID is the process manager, who then takes care of terminating all other processes that are running.

I did many tests and FileBot handles the SIGTERM correctly. I tried to change multiple settings inside FileBot. I'm then stopping or restarting the container (e.g. via `docker stop <container name>` or `docker restart <container name>`) and every time all settings are persisted.

I also tried with unRAID and I didn't see any issue. I'm not able to reproduce what the user is experimenting.

**Comment by jlesage** [comment] 2024-10-17 02:42
I guess that adding the `net.filebot.util.prefs.sync=true` system property would improve robustness in certain situations, but I'm not sure this will fix the user's issue.

**Comment by rednoah** [comment] 2024-10-17 03:56
> When a container is stopped or restarted, the SIGTERM signal is sent to PID 1 inside the container. With this container, PID is the process manager, who then takes care of terminating all other processes that are running.
> 
> I did many tests and FileBot handles the SIGTERM correctly. I tried to change multiple settings inside FileBot. I'm then stopping or restarting the container (e.g. via `docker stop <container name>` or `docker restart <container name>`) and every time all settings are persisted.
> 
> I also tried with unRAID and I didn't see any issue. I'm not able to reproduce what the user is experimenting.

Thanks for looking into that. Sounds like everything is working as it should. Thanks for running tests to confirm. That means the user is likely just killing the process / doing a hard power of / etc. `net.filebot.util.prefs.sync=true` will definitely increase robustness for this corner case.

**Comment by jlesage** [comment] 2024-10-20 23:51
Closing this issue: the `net.filebot.util.prefs.sync=true` system property has been added.

**Closed by jlesage** 2024-10-20 23:51 UTC
Labels: bug
